import type { DataStore } from '@src/data-store/data-store.js';
import type { NLPPipeline, Correlation, Pattern } from '@src/nlp-pipeline/nlp-pipeline.js';
import type { ToneComplianceFilter } from '@src/tone-compliance/tone-compliance-filter.js';
import type { Insight, SupportingSignal } from '@src/models/index.js';
import type { ArchivedDocument } from '@src/models/index.js';

/**
 * Synthesizes across multiple archived documents to identify themes,
 * gaps, and discrepancies between provider perspectives.
 * Requires 2+ documents with extracted text.
 */
export async function synthesizeDocuments(
  childProfileId: string,
  dataStore: DataStore,
  nlpPipeline: NLPPipeline,
  toneFilter: ToneComplianceFilter,
): Promise<Insight | null> {
  const now = new Date();

  // Get all archived documents for this child
  const allDocs = dataStore.getArchivedDocuments(childProfileId);

  // Filter to documents with extracted text
  const docsWithText = allDocs.filter(
    (doc): doc is ArchivedDocument & { extractedText: string } =>
      typeof doc.extractedText === 'string' && doc.extractedText.length > 0,
  );

  if (docsWithText.length < 2) {
    return null;
  }

  // Extract themes from each document (simple keyword-based for MVP)
  const docThemes = docsWithText.map((doc) => ({
    doc,
    themes: extractThemes(doc.extractedText),
    providers: doc.sourceProvider ?? 'Unknown provider',
  }));

  // Find shared themes and discrepancies
  const allThemes = new Map<string, string[]>();
  for (const { doc, themes } of docThemes) {
    for (const theme of themes) {
      const sources = allThemes.get(theme) ?? [];
      sources.push(doc.sourceProvider ?? doc.documentType);
      allThemes.set(theme, sources);
    }
  }

  // Shared themes: present in 2+ documents
  const sharedThemes = [...allThemes.entries()].filter(([, sources]) => sources.length >= 2);

  // Unique themes: present in only 1 document (potential gaps)
  const uniqueThemes = [...allThemes.entries()].filter(([, sources]) => sources.length === 1);

  // Build correlations and patterns for narrative generation
  const correlations: Correlation[] = sharedThemes.map(([theme, sources]) => ({
    factor1: sources[0],
    factor2: sources[1],
    strength: sources.length > 2 ? ('strong' as const) : ('moderate' as const),
    description: `Theme "${theme}" appears across ${sources.length} documents: ${sources.join(', ')}`,
  }));

  const patterns: Pattern[] = [];
  if (uniqueThemes.length > 0) {
    patterns.push({
      type: 'document_gaps',
      description: `${uniqueThemes.length} themes appear in only one document, suggesting potential gaps: ${uniqueThemes.map(([t]) => t).join(', ')}`,
      occurrences: uniqueThemes.length,
    });
  }

  if (sharedThemes.length > 0) {
    patterns.push({
      type: 'cross_document_themes',
      description: `${sharedThemes.length} themes are consistent across multiple documents`,
      occurrences: sharedThemes.length,
    });
  }

  if (correlations.length === 0 && patterns.length === 0) {
    return null;
  }

  // Generate narrative
  const rawNarrative = await nlpPipeline.generateInsightNarrative(correlations, patterns);

  // Apply neuro-affirming reframing of clinical language
  const narrative = toneFilter.reframe(rawNarrative);

  // Build supporting signals
  const supportingSignals: SupportingSignal[] = [
    {
      description: `Synthesized across ${docsWithText.length} documents`,
      observationCount: docsWithText.length,
      contributingFactors: docsWithText.map(
        (d) => `${d.documentType} from ${d.sourceProvider ?? 'unknown provider'}`,
      ),
    },
    ...sharedThemes.map(([theme, sources]): SupportingSignal => ({
      description: `Shared theme: ${theme}`,
      observationCount: sources.length,
      contributingFactors: sources,
    })),
  ];

  const insight: Insight = {
    id: crypto.randomUUID(),
    childProfileId,
    type: 'document_synthesis',
    narrative,
    supportingSignals,
    confidenceScore: docsWithText.length >= 4 ? 'high' : 'medium',
    explainabilityStatement: `This insight was generated by synthesizing ${docsWithText.length} documents, identifying ${sharedThemes.length} shared themes and ${uniqueThemes.length} unique perspectives.`,
    strategyIds: [],
    createdAt: now,
  };

  dataStore.saveInsight(insight);
  return insight;
}

/**
 * Simple keyword-based theme extraction for MVP.
 * Looks for common clinical/educational themes in document text.
 */
function extractThemes(text: string): string[] {
  const themes: string[] = [];
  const lowerText = text.toLowerCase();

  const themeKeywords: Record<string, string[]> = {
    'sensory processing': ['sensory', 'sensory processing', 'sensory seeking', 'sensory sensitivity'],
    'attention': ['attention', 'focus', 'concentration', 'distracti'],
    'executive function': ['executive function', 'planning', 'organization', 'working memory'],
    'social skills': ['social', 'peer', 'friendship', 'social interaction'],
    'communication': ['communication', 'speech', 'language', 'expressive', 'receptive'],
    'behavior': ['behavior', 'behavioral', 'conduct', 'compliance'],
    'anxiety': ['anxiety', 'anxious', 'worry', 'fear'],
    'motor skills': ['motor', 'fine motor', 'gross motor', 'coordination'],
    'academic': ['academic', 'reading', 'math', 'writing', 'learning'],
    'emotional regulation': ['emotional regulation', 'self-regulation', 'dysregulation', 'coping'],
    'sleep': ['sleep', 'insomnia', 'bedtime', 'night waking'],
    'diet and nutrition': ['diet', 'nutrition', 'eating', 'food'],
    'accommodations': ['accommodation', 'iep', 'modification', '504'],
  };

  for (const [theme, keywords] of Object.entries(themeKeywords)) {
    if (keywords.some((kw) => lowerText.includes(kw))) {
      themes.push(theme);
    }
  }

  return themes;
}
