import { EventType } from '../models';

export const EVENT_EMOJIS: Record<EventType, string> = {
  // Alert/negative events
  meltdown: '🌊',
  shutdown: '🔇',
  conflict: '⚡',
  school_incident: '🏫',
  aggression: '😠',
  poor_transitions: '🎢',
  overwhelm: '😢',
  naughty: '😈',
  refusal: '🙅',
  bad_language: '🤬',
  injury: '🤕',
  sneaky: '🥷',
  sick: '🤒',
  
  // Positive/wellness events
  great_day: '🌟',
  positive_behavior: '🌟',
  mood: '😊',
  good_dinner: '😋',
  drew_comics: '🦸',
  stayed_home: '🏠',
  chores: '🧹',
  focus: '🔎',
  reading: '📚',
  kindness: '🫶',
  sibling_harmony: '🫂',
  helpful: '🤝🏻',
  playdate: '👫',
  family_adventure: '🏕️',
  played_outside: '🌳',
  bounceback: '🐦‍🔥',
  good_breakfast: '🍳',
  sports: '🏀',
  party: '🎉',
  dad_bonding: '👨🏻',
  mom_bonding: '👩🏼',
  
  // Physical/health events
  sleep: '😴',
  good_sleep: '😴',
  poor_sleep: '😵',
  diet: '🍎',
  didnt_eat_dinner: '🍽️',
  physical_wellness: '🤒',
  wet_bed: '🛏️',
  tired: '🥱',
  barfed: '🤮',
  
  // Medical
  medication: '💊',
  
  // Neutral/other events
  screen_time: '📱',
  watched_tv: '📺',
  fast_food: '🍟',
  sugar: '🍬',
  messy: '🫗',
  video_games: '🎮',
  toilet_issue: '🚽',
  travel: '✈️',
  vacation: '🌴',
  sporting_event: '🏟️',
  school_trip: '🚌',
  brave: '🦁',
  
  // Custom (placeholder)
  custom: '📝',
};

export function getEventLabel(eventType: EventType): string {
  const labelMap: Record<EventType, string> = {
    meltdown: 'Meltdown',
    shutdown: 'Shutdown',
    conflict: 'Sibling Conflict',
    school_incident: 'School Incident',
    positive_behavior: 'Positive Behavior',
    great_day: 'Great Day',
    mood: 'Mood',
    overwhelm: 'Overwhelm',
    naughty: 'Naughty',
    sleep: 'Sleep',
    good_sleep: 'Good Sleep',
    poor_sleep: 'Poor Sleep',
    diet: 'Diet',
    screen_time: 'Screen Time',
    physical_wellness: 'Physical Wellness',
    medication: 'Medication',
    playdate: 'Playdate',
    watched_tv: 'Watched TV',
    sick: 'Sick',
    family_adventure: 'Family Adventure',
    played_outside: 'Played Outside',
    didnt_eat_dinner: "Didn't Eat Dinner",
    wet_bed: 'Wet Bed',
    good_dinner: 'Good Dinner',
    drew_comics: 'Drew Comics',
    stayed_home: 'Stayed Home',
    aggression: 'Aggression',
    fast_food: 'Fast Food',
    sugar: 'Sugar',
    poor_transitions: 'Poor Transitions',
    chores: 'Chores',
    focus: 'Focus',
    reading: 'Reading',
    kindness: 'Kindness',
    refusal: 'Refusal',
    sibling_harmony: 'Sibling Harmony',
    bad_language: 'Bad Language',
    injury: 'Injury',
    sneaky: 'Sneaky',
    messy: 'Messy',
    helpful: 'Helpful',
    video_games: 'Video Games',
    toilet_issue: 'Toilet Issue',
    dad_bonding: 'Dad Bonding',
    mom_bonding: 'Mom Bonding',
    travel: 'Travel',
    good_breakfast: 'Good Breakfast',
    tired: 'Tired',
    sports: 'Sports',
    party: 'Party',
    bounceback: 'Bounceback',
    barfed: 'Barfed',
    vacation: 'Vacation',
    sporting_event: 'Sporting Event',
    school_trip: 'School Trip',
    brave: 'Brave',
    custom: 'Custom Event',
  };

  return labelMap[eventType] || eventType.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}
